//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmSystemManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public System.DateTime DateModified { get; set; }
        public decimal MinWithDraw { get; set; }
        public decimal MaxWithDraw { get; set; }
        public int NumberPerPage { get; set; }
    }
}
