//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmSystemManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int AccountID { get; set; }
        public int CustID { get; set; }
        public string AccountNo { get; set; }
        public int ODID { get; set; }
        public int WDID { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OverDraft_Limit OverDraft_Limit { get; set; }
        public virtual WithDraw_Limit WithDraw_Limit { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
    }
}
