//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmSystemManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public string CardNo { get; set; }
        public string Status { get; set; }
        public int AccountID { get; set; }
        public string PIN { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public int Attempt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
