//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmSystemManager.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Log
    {
        public int LogID { get; set; }
        public int LogTypeID { get; set; }
        public int ATMID { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Details { get; set; }

        public virtual ATM ATM { get; set; }
        public virtual Card Card { get; set; }
        public virtual LogType LogType { get; set; }


        /*Defind Temp Amount convert string*/
        //public string AmountTemp { get; set { AmountTemp = ChairProgress(Convert.ToDecimal(Amount)); } }

        private string amountTemp;

        public string AmountTemp
        {
            get { return amountTemp; }
            set { amountTemp = ChairProgress(Convert.ToDecimal(Amount)); }
        }

        public string ChairProgress(decimal amount)
        {
            string tempAmout = amount.ToString();
            if (amount < 100000)
            {
                return tempAmout.ToString().Substring(0, 2)
                            + "." + tempAmout.ToString().Substring(2, 3);
            }
            if (amount < 1000000)
            {
                return tempAmout.ToString().Substring(0, 3)
                        + "." + tempAmout.ToString().Substring(3, 3);
            }
            if (amount < 10000000)
            {
                return tempAmout.ToString().Substring(0, 1)
                        + "." + tempAmout.ToString().Substring(1, 3)
                        + "." + tempAmout.ToString().Substring(4, 3);
            }
            if (amount < 100000000)
            {
                return tempAmout.ToString().Substring(0, 2)
                        + "." + tempAmout.ToString().Substring(2, 3)
                        + "." + tempAmout.ToString().Substring(5, 3);
            }
            return tempAmout;
        }
    }
}
